server { # Блок віртуального хоста (окремий сайт/конфігурація сервера)

    listen 80; # Слухати HTTP-запити на 80 порту всередині контейнера
    server_name localhost; # Ім'я хоста (домен), для якого працює цей server-блок (тут локально)
    index index.html; # Файл за замовчуванням, який віддаємо, якщо запитують директорію
    root /usr/share/nginx/html; # Коренева папка зі статичними файлами (тут змонтований ./client)

    location / { # Правила для всіх запитів на фронтенд (головний шлях)
        try_files $uri$args $uri$args/ /index.html;
        # try_files перевіряє, чи існує файл/шлях у статичних ресурсах:
        # 1) $uri$args   -> файл за шляхом з урахуванням query string
        # 2) $uri$args/  -> директорія за шляхом з урахуванням query string
        # 3) /index.html -> якщо нічого не знайдено, віддаємо index.html (типово для SPA: React/Vue/Angular)
    }

    location /api/ { # Усі запити, що починаються з /api/, прокидуємо на бекенд
        proxy_pass http://app:5001/;
        # proxy_pass пересилає запит на інший сервіс (тут на контейнер "app" у docker-compose мережі)
        # ВАЖЛИВО: "app" — це ім'я сервісу в compose, Docker DNS його резолвить

        proxy_set_header Host $host; # Передаємо бекенду оригінальний Host (корисно для логіки/логів)
        proxy_set_header Connection "upgrade"; # Готуємо з'єднання до upgrade (часто для WebSocket)
        proxy_set_header Upgrade $http_upgrade; # Передаємо заголовок Upgrade (потрібно для WebSocket)
    }
}